/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Thu Jan 18 14:16:00 2018. */

#include "kurapayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t kuradatatypes_KuraPayload_fields[6] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC  , FIRST, kuradatatypes_KuraPayload, timestamp, timestamp, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload, position, timestamp, &kuradatatypes_KuraPayload_KuraPosition_fields),
    PB_FIELD(  3, EXTENSION, OPTIONAL, CALLBACK, OTHER, kuradatatypes_KuraPayload, extensions, position, 0),
    PB_FIELD(5000, MESSAGE , REPEATED, CALLBACK, OTHER, kuradatatypes_KuraPayload, metric, extensions, &kuradatatypes_KuraPayload_KuraMetric_fields),
    PB_FIELD(5001, BYTES   , OPTIONAL, CALLBACK, OTHER, kuradatatypes_KuraPayload, body, metric, 0),
    PB_LAST_FIELD
};

const pb_field_t kuradatatypes_KuraPayload_KuraMetric_fields[10] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, kuradatatypes_KuraPayload_KuraMetric, name, name, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, type, name, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, double_value, type, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, float_value, double_value, 0),
    PB_FIELD(  5, INT64   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, long_value, float_value, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, int_value, long_value, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraMetric, bool_value, int_value, 0),
    PB_FIELD(  8, STRING  , OPTIONAL, CALLBACK, OTHER, kuradatatypes_KuraPayload_KuraMetric, string_value, bool_value, 0),
    PB_FIELD(  9, BYTES   , OPTIONAL, CALLBACK, OTHER, kuradatatypes_KuraPayload_KuraMetric, bytes_value, string_value, 0),
    PB_LAST_FIELD
};

const pb_field_t kuradatatypes_KuraPayload_KuraPosition_fields[10] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, kuradatatypes_KuraPayload_KuraPosition, latitude, latitude, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, longitude, latitude, 0),
    PB_FIELD(  3, DOUBLE  , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, altitude, longitude, 0),
    PB_FIELD(  4, DOUBLE  , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, precision, altitude, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, heading, precision, 0),
    PB_FIELD(  6, DOUBLE  , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, speed, heading, 0),
    PB_FIELD(  7, INT64   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, timestamp, speed, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, satellites, timestamp, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, kuradatatypes_KuraPayload_KuraPosition, status, satellites, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(kuradatatypes_KuraPayload, position) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_kuradatatypes_KuraPayload_kuradatatypes_KuraPayload_KuraMetric_kuradatatypes_KuraPayload_KuraPosition)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for kuradatatypes_KuraPayload.body is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
